name: Build

on:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      matrix:
        os: [	"ubuntu-16.04", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: ${{ matrix.os == 'macos-10.15' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:george-edison55/cmake-3.x
        sudo apt-get update
        sudo apt-get install -y cmake cmake-data git build-essential autoconf texinfo bison flex pkg-config
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: vitasdk-${{ matrix.os }}
        path: build/*.tar.bz2
